[env:esp32-s3-n16r8]
platform  = espressif32
board     = esp32-s3-devkitc-1
framework = arduino

monitor_speed   = 115200
upload_speed    = 921600
upload_protocol = esptool

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=0
    -DBOARD_HAS_PSRAM
    -DELEGANTOTA_USE_ASYNC_WEBSERVER=1

board_build.arduino.memory_type = qio_opi
board_build.partitions          = default_16MB.csv
board_build.flash_size          = 16MB
board_build.flash_mode          = qio
board_build.psram_type          = opi
board_upload.flash_size         = 16MB

lib_deps =
    ; HUB75 matrix driver
    mrfaptastic/ESP32 HUB75 LED MATRIX PANEL DMA Display @ ^3.0.14

    ; Adafruit GFX (required by HUB75 lib)
    adafruit/Adafruit GFX Library @ ^1.12.5

    ; Async HTTP server + WebSocket
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    https://github.com/me-no-dev/AsyncTCP.git

    ; JSON
    bblanchon/ArduinoJson @ ^7.2.0

    ; NTP
    arduino-libraries/NTPClient @ ^3.2.1

    ; OTA
    ayushsharma82/ElegantOTA @ ^3.1.5

    ; GIF decoder
    bitbank2/AnimatedGIF @ ^2.1.0
